<?xml version="1.0" encoding="utf-8"?><Database Name="FlowersShop" Class="LinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-JLJ2TBG;Initial Catalog=FlowersShop;Integrated Security=True" SettingsObjectName="rac.Properties.Settings" SettingsPropertyName="FlowersShopConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="IDHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_ChiTietHoaDon" Member="SanPham" ThisKey="IDSP" OtherKey="IDSP" Type="SanPham" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="IDHoaDon" OtherKey="IDHoaDon" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="IDSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SanPham_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="IDSP" OtherKey="IDSP" Type="ChiTietHoaDon" />
      <Association Name="SanPham_KhoHang" Member="KhoHangs" ThisKey="IDSP" OtherKey="IDSP" Type="KhoHang" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="IDHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="IDHoaDon" OtherKey="IDHoaDon" Type="ChiTietHoaDon" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="IDNV" OtherKey="IDNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoHang" Member="KhoHangs">
    <Type Name="KhoHang">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_KhoHang" Member="SanPham" ThisKey="IDSP" OtherKey="IDSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiNhanVien" Member="LoaiNhanViens">
    <Type Name="LoaiNhanVien">
      <Column Name="IDLoaiNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiNhanVien_NhanVien" Member="NhanViens" ThisKey="IDLoaiNV" OtherKey="IDLoaiNV" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="IDNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TuoiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDLoaiNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="IDNV" OtherKey="IDNV" Type="HoaDon" />
      <Association Name="NhanVien_NhapHang" Member="NhapHangs" ThisKey="IDNV" OtherKey="IDNV" Type="NhapHang" />
      <Association Name="LoaiNhanVien_NhanVien" Member="LoaiNhanVien" ThisKey="IDLoaiNV" OtherKey="IDLoaiNV" Type="LoaiNhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhapHang" Member="NhapHangs">
    <Type Name="NhapHang">
      <Column Name="IDNhap" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNguonNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongTienNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_NhapHang" Member="NhanVien" ThisKey="IDNV" OtherKey="IDNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_DeleteKhoHang" Method="sp_DeleteKhoHang">
    <Parameter Name="stt" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_updateSanPham" Method="sp_updateSanPham">
    <Parameter Name="idsp" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tensp" Parameter="tensp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="mota" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteNhanVien" Method="sp_DeleteNhanVien">
    <Parameter Name="IDNV" Parameter="iDNV" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteSanPham" Method="sp_DeleteSanPham">
    <Parameter Name="idsp" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getNhanVienByID" Method="sp_getNhanVienByID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_getNhanVienByIDResult">
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_insertKhoHang" Method="sp_insertKhoHang">
    <Parameter Name="idsp" Type="System.Int32" DbType="Int" />
    <Parameter Name="NgayNhap" Parameter="ngayNhap" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NgayHetHan" Parameter="ngayHetHan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Soluong" Parameter="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_insertNhanVien" Method="sp_insertNhanVien">
    <Parameter Name="TenNv" Parameter="tenNv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Tuoi" Parameter="tuoi" Type="System.Int32" DbType="Int" />
    <Parameter Name="userid" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="userpassword" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="idloainv" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_insertSanPham" Method="sp_insertSanPham">
    <Parameter Name="Tensp" Parameter="tensp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gia" Type="System.Int32" DbType="Int" />
    <Parameter Name="mota" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_LoadKhoHang" Method="sp_LoadKhoHang">
    <ElementType Name="sp_LoadKhoHangResult">
      <Column Name="IDSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_LoadNhanVien" Method="sp_LoadNhanVien">
    <ElementType Name="sp_LoadNhanVienResult">
      <Column Name="IDNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TuoiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDLoaiNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_LoadSanPham" Method="sp_LoadSanPham">
    <ElementType Name="sp_LoadSanPhamResult">
      <Column Name="IDSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_updateKhoHang" Method="sp_updateKhoHang">
    <Parameter Name="STT" Parameter="sTT" Type="System.Int32" DbType="Int" />
    <Parameter Name="idsp" Type="System.Int32" DbType="Int" />
    <Parameter Name="NgayNhap" Parameter="ngayNhap" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NgayHetHan" Parameter="ngayHetHan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Soluong" Parameter="soluong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_updateNhanVien" Method="sp_updateNhanVien">
    <Parameter Name="idnv" Type="System.Int32" DbType="Int" />
    <Parameter Name="TenNv" Parameter="tenNv" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Tuoi" Parameter="tuoi" Type="System.Int32" DbType="Int" />
    <Parameter Name="userid" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="userpassword" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="idloainv" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_updatePasswordNhanVien" Method="sp_updatePasswordNhanVien">
    <Parameter Name="idnv" Type="System.Int32" DbType="Int" />
    <Parameter Name="userpassword" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.checkAccount" Method="checkAccount" IsComposable="true">
    <Parameter Name="userID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>